apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-hub
  template:
    metadata:
      labels:
        app: central-hub
    spec:
      serviceAccountName: central-hub-sa
      nodeSelector:
        kubernetes.io/hostname: jin03-asus-tuf-dash-f15-fx516pr-fx516pr
    
      tolerations:
      - operator: "Exists"  
      
      containers:
      - name: central-hub
        image: jny123/central-hub:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: central-hub
spec:
  type: NodePort
  selector:
    app: central-hub
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30005